---
  - name: "Systemwide changes"
    hosts: localhost
    connection: local
    become: yes
    vars:
      HOSTNAME: "UbuntuWSL"

    tasks:

      - name: "Add PPA that provides the latest stable upstream Git version"
        ansible.builtin.apt_repository:
          repo: ppa:git-core/ppa

      - name: "Updating system"
        ansible.builtin.apt:
          update_cache: yes
          upgrade: full
        tags: update

      - name: "Installing packages"
        ansible.builtin.apt:
          cache_valid_time: 600
          update_cache: yes
          install_recommends: yes
          name:
            - ansible-doc
            - aptitude
            - git
            - joe
            - mc
            - python3-pip
            - geany
            - geany-plugins
            - adwaita-icon-theme-full
            - meld
          state: present
        tags: install

      - name: "Cleaning the local apt cache"
        ansible.builtin.apt:
          autoclean: yes

      - name: "Create /etc/wsl.conf from template wsl.conf.j2"
        ansible.builtin.template:
          src: ./wsl.conf.j2
          dest: /etc/wsl.conf
        tags: wsl.conf
